let name = 'one';
let one = 1;
console.log(name);
console.log(one);
let name2 = 'two';
let two = 2;
console.log(name2);
console.log(two);
let name3 = 'three';
let three = 3;
console.log(name3);
console.log(three);
let name4 = 'tab';
let tab = [one, two, three];
console.log(name4);
console.log(tab);